FROM rust:1.45.2 as builder
WORKDIR /usr/src/wallpaper_service
ARG WALLPAPER_SOURCE_URL=https://github.com/ZaMaZaN4iK/wallpaper_server.git
ARG CACHE_DATE=2020-01-01
RUN git clone --single-branch --branch master ${WALLPAPER_SOURCE_URL}
WORKDIR wallpaper_server
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/wallpaper_service /usr/local/bin/wallpaper_service

RUN groupadd -g 2000 wallpaper_user && \
    useradd -r -u 2000 -g wallpaper_user wallpaper_user && \
    chown wallpaper_user:wallpaper_user /usr/local/bin/wallpaper_service
USER wallpaper_user

WORKDIR /usr/local/bin
ENTRYPOINT ["/usr/local/bin/wallpaper_service"]
