FROM rust:1.44 as builder
WORKDIR /usr/src/wallpaper_service
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /usr/local/cargo/bin/wallpaper_service /usr/local/bin/wallpaper_service
CMD ["wallpaper_service"]